# Form implementation generated from reading ui file 'mortalCombat.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class player:
    # Special method: constructor. Automatically called when an object is created from the class
    def __init__(self, name, speed, power, agility):
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
        
    def modify_stats(self, speed, power, agility):
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility

class Ui_mortalCombat(object):
    def setupUi(self, mortalCombat):
        mortalCombat.setObjectName("mortalCombat")
        mortalCombat.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        mortalCombat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mortalCombat)
        self.centralwidget.setObjectName("centralwidget")
        self.tbMortalCombat = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMortalCombat.setGeometry(QtCore.QRect(0, 0, 781, 551))
        self.tbMortalCombat.setObjectName("tbMortalCombat")
        self.tbCreatePlayer = QtWidgets.QWidget()
        self.tbCreatePlayer.setObjectName("tbCreatePlayer")
        self.lblName = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblName.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtName.setGeometry(QtCore.QRect(140, 30, 113, 20))
        self.txtName.setObjectName("txtName")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblSpeed.setGeometry(QtCore.QRect(30, 90, 81, 16))
        self.lblSpeed.setObjectName("lblSpeed")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtSpeed.setGeometry(QtCore.QRect(140, 90, 113, 20))
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblPower = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblPower.setGeometry(QtCore.QRect(30, 150, 91, 16))
        self.lblPower.setObjectName("lblPower")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtPower.setGeometry(QtCore.QRect(140, 150, 113, 20))
        self.txtPower.setObjectName("txtPower")
        self.lblAgility = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblAgility.setGeometry(QtCore.QRect(30, 230, 81, 16))
        self.lblAgility.setObjectName("lblAgility")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtAgility.setGeometry(QtCore.QRect(140, 230, 113, 20))
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreate = QtWidgets.QPushButton(parent=self.tbCreatePlayer)
        self.btnCreate.setGeometry(QtCore.QRect(150, 330, 101, 23))
        self.btnCreate.setObjectName("btnCreate")
        self.tbMortalCombat.addTab(self.tbCreatePlayer, "")
        self.tbModifyPlayer = QtWidgets.QWidget()
        self.tbModifyPlayer.setObjectName("tbModifyPlayer")
        self.lblExistingPlayers = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblExistingPlayers.setGeometry(QtCore.QRect(250, 50, 101, 16))
        self.lblExistingPlayers.setObjectName("lblExistingPlayers")
        self.lstExistingPlayers = QtWidgets.QListWidget(parent=self.tbModifyPlayer)
        self.lstExistingPlayers.setGeometry(QtCore.QRect(180, 80, 256, 192))
        self.lstExistingPlayers.setObjectName("lstExistingPlayers")
        self.lblCurrentSpeed = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentSpeed.setGeometry(QtCore.QRect(70, 310, 47, 13))
        self.lblCurrentSpeed.setObjectName("lblCurrentSpeed")
        self.txtCurrentSpeed = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentSpeed.setGeometry(QtCore.QRect(30, 340, 113, 20))
        self.txtCurrentSpeed.setObjectName("txtCurrentSpeed")
        self.lblCurrentPower = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentPower.setGeometry(QtCore.QRect(260, 310, 47, 13))
        self.lblCurrentPower.setObjectName("lblCurrentPower")
        self.txtCurrentPower = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentPower.setGeometry(QtCore.QRect(220, 340, 113, 20))
        self.txtCurrentPower.setObjectName("txtCurrentPower")
        self.lvlCurrentAgility = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lvlCurrentAgility.setGeometry(QtCore.QRect(480, 310, 47, 13))
        self.lvlCurrentAgility.setObjectName("lvlCurrentAgility")
        self.txtCurrentAgility = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentAgility.setGeometry(QtCore.QRect(440, 340, 113, 20))
        self.txtCurrentAgility.setObjectName("txtCurrentAgility")
        self.btnModify = QtWidgets.QPushButton(parent=self.tbModifyPlayer)
        self.btnModify.setGeometry(QtCore.QRect(290, 420, 101, 23))
        self.btnModify.setObjectName("btnModify")
        self.tbMortalCombat.addTab(self.tbModifyPlayer, "")
        mortalCombat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mortalCombat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        mortalCombat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mortalCombat)
        self.statusbar.setObjectName("statusbar")
        mortalCombat.setStatusBar(self.statusbar)

        self.retranslateUi(mortalCombat)
        self.tbMortalCombat.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mortalCombat)
        
        self.created_players = {}
        
        self.btnCreate.clicked.connect(self.create_player)
        
        self.lstExistingPlayers.itemClicked.connect(self.display_stats)
        
        self.btnModify.clicked.connect(self.modify_player_stats)
        
    def modify_player_stats(self):
        try:
            name = self.lstExistingPlayers.currentItem().text()
            speed = self.txtCurrentSpeed.text()
            power = self.txtCurrentPower.text()
            agility = self.txtCurrentAgility.text()
            
            playerobject = self.created_players.get(name)
            playerobject.modify_stats(speed, power, agility)
        except Exception as e:
            print(e)
            print(type(e))
        
    def display_stats(self):
        try:
            name = self.lstExistingPlayers.currentItem().text()
            player_object = self.created_players.get(name)
            self.txtCurrentSpeed.setText(f"{player_object.player_speed}")
            self.txtCurrentPower.setText(f"{player_object.player_power}")
            self.txtCurrentAgility.setText(f"{player_object.player_agility}")
        except Exception as e:
            print(e)
            print(type(e))
        
    def create_player(self):
        try:
            name = self.txtName.text()
            speed = self.txtSpeed.text()
            power = self.txtPower.text()
            agility = self.txtAgility.text()
            
            player_object = player(name, speed, power, agility)
            self.created_players[name] = player_object
            self.lstExistingPlayers.addItem(name)
        except Exception as e:
            print(e)
            print(type(e))
            
            

    def retranslateUi(self, mortalCombat):
        _translate = QtCore.QCoreApplication.translate
        mortalCombat.setWindowTitle(_translate("mortalCombat", "Mortal Combat"))
        self.lblName.setText(_translate("mortalCombat", "Enter Name"))
        self.lblSpeed.setText(_translate("mortalCombat", "Enter Speed"))
        self.lblPower.setText(_translate("mortalCombat", "Enter Power"))
        self.lblAgility.setText(_translate("mortalCombat", "Enter Agility"))
        self.btnCreate.setText(_translate("mortalCombat", "Create Player"))
        self.tbMortalCombat.setTabText(self.tbMortalCombat.indexOf(self.tbCreatePlayer), _translate("mortalCombat", "Create Player"))
        self.lblExistingPlayers.setText(_translate("mortalCombat", "Existing Players"))
        self.lblCurrentSpeed.setText(_translate("mortalCombat", "Speed"))
        self.lblCurrentPower.setText(_translate("mortalCombat", "Power"))
        self.lvlCurrentAgility.setText(_translate("mortalCombat", "Agility"))
        self.btnModify.setText(_translate("mortalCombat", "Modify Player"))
        self.tbMortalCombat.setTabText(self.tbMortalCombat.indexOf(self.tbModifyPlayer), _translate("mortalCombat", "Modify Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mortalCombat = QtWidgets.QMainWindow()
    ui = Ui_mortalCombat()
    ui.setupUi(mortalCombat)
    mortalCombat.show()
    sys.exit(app.exec())
