# Form implementation generated from reading ui file 'firstwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from secondwindow import Ui_secondWindow

class Ui_firstWindow(object):
    def setupUi(self, firstWindow):
        firstWindow.setObjectName("firstWindow")
        firstWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        firstWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=firstWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblText.setGeometry(QtCore.QRect(180, 120, 71, 16))
        self.lblText.setObjectName("lblText")
        self.txtInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(280, 120, 113, 20))
        self.txtInput.setObjectName("txtInput")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(270, 200, 151, 23))
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnTransfer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTransfer.setGeometry(QtCore.QRect(290, 270, 111, 23))
        self.btnTransfer.setObjectName("btnTransfer")
        firstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=firstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        firstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=firstWindow)
        self.statusbar.setObjectName("statusbar")
        firstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(firstWindow)
        QtCore.QMetaObject.connectSlotsByName(firstWindow)
        
        self.btnDisplay.clicked.connect(self.display_window)
        self.btnTransfer.clicked.connect(self.transfer_text)
        
    def transfer_text(self):
        # Get the input text from the user in the first wwindow
        input_text = self.txtInput.text()
        # The if statement will check if the object secondui has been created
        if hasattr(self, "secondui"):
        # Setting the input text entered into the first window to the line edit widget in the second window
            self.secondui.txtTransferredText.setText(input_text)
        else:
            print("Second window not initialized")
        
    def display_window(self):
        # Create a new window instance
        self.window = QtWidgets.QMainWindow()
        # Create an object of the second application window
        self.secondui = Ui_secondWindow()
        self.secondui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, firstWindow):
        _translate = QtCore.QCoreApplication.translate
        firstWindow.setWindowTitle(_translate("firstWindow", "First Window"))
        self.lblText.setText(_translate("firstWindow", "Enter text"))
        self.btnDisplay.setText(_translate("firstWindow", "Display second window"))
        self.btnTransfer.setText(_translate("firstWindow", "Transfer text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstWindow = QtWidgets.QMainWindow()
    ui = Ui_firstWindow()
    ui.setupUi(firstWindow)
    firstWindow.show()
    sys.exit(app.exec())
