# Form implementation generated from reading ui file 'secondwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_secondWindow(object):
    def setupUi(self, secondWindow):
        secondWindow.setObjectName("secondWindow")
        secondWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        secondWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=secondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTransferredText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTransferredText.setGeometry(QtCore.QRect(190, 100, 111, 16))
        self.lblTransferredText.setObjectName("lblTransferredText")
        self.txtTransferredText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTransferredText.setGeometry(QtCore.QRect(350, 100, 113, 20))
        self.txtTransferredText.setObjectName("txtTransferredText")
        secondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=secondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        secondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=secondWindow)
        self.statusbar.setObjectName("statusbar")
        secondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(secondWindow)
        QtCore.QMetaObject.connectSlotsByName(secondWindow)

    def retranslateUi(self, secondWindow):
        _translate = QtCore.QCoreApplication.translate
        secondWindow.setWindowTitle(_translate("secondWindow", "Second Window"))
        self.lblTransferredText.setText(_translate("secondWindow", "Transferred Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secondWindow = QtWidgets.QMainWindow()
    ui = Ui_secondWindow()
    ui.setupUi(secondWindow)
    secondWindow.show()
    sys.exit(app.exec())
