# Form implementation generated from reading ui file 'ticketPurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ticketPurchase(object):
    def setupUi(self, ticketPurchase):
        ticketPurchase.setObjectName("ticketPurchase")
        ticketPurchase.resize(1519, 1098)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        ticketPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=ticketPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.tbMainTab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMainTab.setGeometry(QtCore.QRect(10, 10, 1461, 1021))
        self.tbMainTab.setObjectName("tbMainTab")
        self.tbTicketPurchase = QtWidgets.QWidget()
        self.tbTicketPurchase.setObjectName("tbTicketPurchase")
        self.lblName = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblName.setGeometry(QtCore.QRect(290, 100, 81, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtName.setGeometry(QtCore.QRect(430, 100, 113, 20))
        self.txtName.setObjectName("txtName")
        self.lblAge = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblAge.setGeometry(QtCore.QRect(290, 150, 71, 16))
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtAge.setGeometry(QtCore.QRect(430, 150, 113, 20))
        self.txtAge.setObjectName("txtAge")
        self.lblTicketType = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblTicketType.setGeometry(QtCore.QRect(290, 210, 111, 16))
        self.lblTicketType.setObjectName("lblTicketType")
        self.cmbTicketType = QtWidgets.QComboBox(parent=self.tbTicketPurchase)
        self.cmbTicketType.setGeometry(QtCore.QRect(428, 210, 111, 22))
        self.cmbTicketType.setObjectName("cmbTicketType")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnCalculate.setGeometry(QtCore.QRect(230, 420, 75, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(350, 420, 75, 23))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnClear.setGeometry(QtCore.QRect(480, 420, 75, 23))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnExit.setGeometry(QtCore.QRect(610, 420, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.lblCost = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblCost.setGeometry(QtCore.QRect(290, 520, 111, 16))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtCost.setGeometry(QtCore.QRect(430, 520, 113, 20))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.grpNumberOfTickets = QtWidgets.QGroupBox(parent=self.tbTicketPurchase)
        self.grpNumberOfTickets.setGeometry(QtCore.QRect(670, 220, 231, 131))
        self.grpNumberOfTickets.setObjectName("grpNumberOfTickets")
        self.rd1 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd1.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rd1.setObjectName("rd1")
        self.rd2 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd2.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.rd2.setObjectName("rd2")
        self.rd3 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd3.setGeometry(QtCore.QRect(10, 90, 82, 17))
        self.rd3.setObjectName("rd3")
        self.tbMainTab.addTab(self.tbTicketPurchase, "")
        self.tbPurchasesMade = QtWidgets.QWidget()
        self.tbPurchasesMade.setObjectName("tbPurchasesMade")
        self.lstPurchasesMade = QtWidgets.QListWidget(parent=self.tbPurchasesMade)
        self.lstPurchasesMade.setGeometry(QtCore.QRect(110, 100, 1211, 501))
        self.lstPurchasesMade.setObjectName("lstPurchasesMade")
        self.lblPurchasesMade = QtWidgets.QLabel(parent=self.tbPurchasesMade)
        self.lblPurchasesMade.setGeometry(QtCore.QRect(120, 60, 101, 16))
        self.lblPurchasesMade.setObjectName("lblPurchasesMade")
        self.tbMainTab.addTab(self.tbPurchasesMade, "")
        ticketPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ticketPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1519, 22))
        self.menubar.setObjectName("menubar")
        ticketPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ticketPurchase)
        self.statusbar.setObjectName("statusbar")
        ticketPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(ticketPurchase)
        self.tbMainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ticketPurchase)
        # Create an empty dictionary to store price data
        self.price_data = {}
        
        self.load_data("price.txt")
        
        self.btnCalculate.clicked.connect(self.calculate_cost)
        
        self.btnPurchase.clicked.connect(self.purchase_ticket)
        
        # The event to identify a change in the tab selected
        self.tbMainTab.currentChanged.connect(self.display_data)
        
        self.btnClear.clicked.connect(self.clear)
        
        self.btnExit.clicked.connect(self.exit_application)
        
    def exit_application(self):
        QtWidgets.QApplication.quit()
        
    def clear(self):
        # Clear the name line edit widget
        self.txtName.clear()
        # Clear the age line edit widget
        self.txtAge.clear()
        # Set the ticket type selection to Toplevel
        self.cmbTicketType.setCurrentIndex(0)
        # Set the radio button selection to rd1
        self.rd1.setChecked(True)
        # Clear the cost line edit widget
        self.txtCost.clear()
        
    def display_data(self):
        try:
            # Identify which tab the user has clicked. Index == 1 indicates the purchases made tab.
            if(self.tbMainTab.currentIndex() ==1):
                # Open the file containing the purchases in the read mode, read each line and display the line to a list widget
                with open("Purchases_made.txt", "r") as f:
                    for line in f:
                        self.lstPurchasesMade.addItem(line)
            else:
                # If a user clicks the ticket purchase tab, clear the list widget
                self.lstPurchasesMade.clear()
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
            
        
    def purchase_ticket(self):
        try:
            # Get the name entered in the line edit widget
            name = self.txtName.text()
            # Get the age entered in the line edit widget
            age = int(self.txtAge.text())
            # Get the ticket type selection in the combo box
            current_selection = self.cmbTicketType.currentText()
            # Get the radio button clicked
            if(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 1
            # Open the file in the append mode and write the name, age, ticket type and number of tickets
            with open("Purchases_made.txt", "a") as f:
                f.write(f"{name}    {age}   {current_selection}     {number_of_tickets} \n")
            
            # Add a message box to display save operation was successful
            
                
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
        
    def calculate_cost(self):
        try:
            # Get the current ticket selection from the combo box
            current_selection = self.cmbTicketType.currentText()
            # Get the radio button clicked by the user
            if(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else:
                number_of_tickets = 1
                
            # Get price of ticket type from dictionary
            price = self.price_data.get(current_selection)
            # Caclulate the cost of the transaction
            cost = price*number_of_tickets
            # Display the cost using the line edit widget
            self.txtCost.setText(f"${cost:.2f}")
        except:
            print("There was an unexpected error")
        finally:
            print("Closing any open DB connections")
            
        
    def load_data(self, filename):
        try:
            with open(filename, "r") as f:
                for line in f:
                    # Data is a list that will contain the ticket type as the first item and price as the second item after the split
                    data = line.split(",")
                    self.price_data[data[0]] = int(data [1])
        except FileNotFoundError:
            print("The file could not be opened")
        except:
            print("There was an unexpected error:")
        finally:
            print("Closing any open DB connections")
        

    def retranslateUi(self, ticketPurchase):
        _translate = QtCore.QCoreApplication.translate
        ticketPurchase.setWindowTitle(_translate("ticketPurchase", "Ticket Purchase"))
        self.lblName.setText(_translate("ticketPurchase", "Enter Name"))
        self.lblAge.setText(_translate("ticketPurchase", "Enter Age"))
        self.lblTicketType.setText(_translate("ticketPurchase", "Select ticket type"))
        self.cmbTicketType.setItemText(0, _translate("ticketPurchase", "Toplevel"))
        self.cmbTicketType.setItemText(1, _translate("ticketPurchase", "Midlevel"))
        self.cmbTicketType.setItemText(2, _translate("ticketPurchase", "Courtside"))
        self.btnCalculate.setText(_translate("ticketPurchase", "Calculate"))
        self.btnPurchase.setText(_translate("ticketPurchase", "Purchase"))
        self.btnClear.setText(_translate("ticketPurchase", "Clear"))
        self.btnExit.setText(_translate("ticketPurchase", "Exit"))
        self.lblCost.setText(_translate("ticketPurchase", "Cost of Purchase"))
        self.grpNumberOfTickets.setTitle(_translate("ticketPurchase", "Number of tickets"))
        self.rd1.setText(_translate("ticketPurchase", "1"))
        self.rd2.setText(_translate("ticketPurchase", "2"))
        self.rd3.setText(_translate("ticketPurchase", "3"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbTicketPurchase), _translate("ticketPurchase", "Ticket Purchase"))
        self.lblPurchasesMade.setText(_translate("ticketPurchase", "Purchases Made"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbPurchasesMade), _translate("ticketPurchase", "Purchases Made"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ticketPurchase = QtWidgets.QMainWindow()
    ui = Ui_ticketPurchase()
    ui.setupUi(ticketPurchase)
    ticketPurchase.show()
    sys.exit(app.exec())
