# Form implementation generated from reading ui file 'projectOne.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_raminsCoffeeShack(object):
    def setupUi(self, raminsCoffeeShack):
        raminsCoffeeShack.setObjectName("raminsCoffeeShack")
        raminsCoffeeShack.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        raminsCoffeeShack.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=raminsCoffeeShack)
        self.centralwidget.setObjectName("centralwidget")
        self.lblRaminsCoffeeShack = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRaminsCoffeeShack.setGeometry(QtCore.QRect(290, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblRaminsCoffeeShack.setFont(font)
        self.lblRaminsCoffeeShack.setObjectName("lblRaminsCoffeeShack")
        self.lblNumberofLattes = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumberofLattes.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.lblNumberofLattes.setObjectName("lblNumberofLattes")
        self.lblNumberofCappuccinos = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumberofCappuccinos.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.lblNumberofCappuccinos.setObjectName("lblNumberofCappuccinos")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 151, 16))
        self.label_3.setObjectName("label_3")
        self.lblSize = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSize.setGeometry(QtCore.QRect(10, 170, 151, 16))
        self.lblSize.setObjectName("lblSize")
        self.txtLatteValue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLatteValue.setGeometry(QtCore.QRect(380, 50, 113, 20))
        self.txtLatteValue.setObjectName("txtLatteValue")
        self.txtSizeValue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSizeValue.setGeometry(QtCore.QRect(380, 170, 113, 20))
        self.txtSizeValue.setObjectName("txtSizeValue")
        self.txtEspressoValue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtEspressoValue.setGeometry(QtCore.QRect(380, 130, 113, 20))
        self.txtEspressoValue.setObjectName("txtEspressoValue")
        self.txtCappucinnoValue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCappucinnoValue.setGeometry(QtCore.QRect(380, 90, 113, 20))
        self.txtCappucinnoValue.setObjectName("txtCappucinnoValue")
        self.lblLatteCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLatteCost.setGeometry(QtCore.QRect(510, 50, 71, 16))
        self.lblLatteCost.setObjectName("lblLatteCost")
        self.lblListofSize = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblListofSize.setGeometry(QtCore.QRect(510, 170, 201, 16))
        self.lblListofSize.setObjectName("lblListofSize")
        self.lblEspressoCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEspressoCost.setGeometry(QtCore.QRect(510, 130, 71, 16))
        self.lblEspressoCost.setObjectName("lblEspressoCost")
        self.lblCappuccinoCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCappuccinoCost.setGeometry(QtCore.QRect(510, 90, 71, 16))
        self.lblCappuccinoCost.setObjectName("lblCappuccinoCost")
        self.lblTip = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTip.setGeometry(QtCore.QRect(10, 260, 141, 16))
        self.lblTip.setObjectName("lblTip")
        self.tipValue = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tipValue.setGeometry(QtCore.QRect(380, 260, 113, 20))
        self.tipValue.setObjectName("tipValue")
        self.btnSubmitOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSubmitOrder.setGeometry(QtCore.QRect(10, 330, 211, 23))
        self.btnSubmitOrder.setObjectName("btnSubmitOrder")
        self.lblTotalCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalCost.setGeometry(QtCore.QRect(10, 390, 131, 16))
        self.lblTotalCost.setObjectName("lblTotalCost")
        self.txtTotalCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalCost.setGeometry(QtCore.QRect(380, 390, 113, 20))
        self.txtTotalCost.setReadOnly(True)
        self.txtTotalCost.setObjectName("txtTotalCost")
        self.lblDollarSign = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDollarSign.setGeometry(QtCore.QRect(500, 260, 47, 13))
        self.lblDollarSign.setObjectName("lblDollarSign")
        raminsCoffeeShack.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=raminsCoffeeShack)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        raminsCoffeeShack.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=raminsCoffeeShack)
        self.statusbar.setObjectName("statusbar")
        raminsCoffeeShack.setStatusBar(self.statusbar)

        self.retranslateUi(raminsCoffeeShack)
        QtCore.QMetaObject.connectSlotsByName(raminsCoffeeShack)
        
        # Connects the button to the function that calculates the total
        self.btnSubmitOrder.clicked.connect(self.calculate_total)
        
    def calculate_total(self):
        # These codes will get all the inputs from the text boxes. If the Text box is empty then it will default to 0
        num_lattes = int(self.txtLatteValue.text() or 0)
        num_cappuccinos = int(self.txtCappucinnoValue.text() or 0)
        num_espressos = int(self.txtEspressoValue.text() or 0)
        size = self.txtSizeValue.text()
        tip_amount = int(self.tipValue.text() or 0) 

        # These codes set the price for each type of coffe, will come in handy with the calculation lines
        latte_price = 4.50
        cappuccino_price = 5.00
        espresso_price = 5.50
        
        # These codes calculate the total (before tip and upsize charge)
        total = (num_lattes * latte_price) + \
            (num_cappuccinos * cappuccino_price) + \
            (num_espressos * espresso_price)
        
        # These lines make sure that if the user selects large, the upcharge will be applied 
        total_coffees = num_lattes + num_cappuccinos + num_espressos
        if size == "Large":   
            total = total + (total_coffees * 2)
            
        # This line adds the tip (If one is entered)
        total = total + tip_amount
           
        # And finally this line displays the final total along with the $ symbol
        self.txtTotalCost.setText("$" + str(total))

        

    def retranslateUi(self, raminsCoffeeShack):
        _translate = QtCore.QCoreApplication.translate
        raminsCoffeeShack.setWindowTitle(_translate("raminsCoffeeShack", "Ramin\'s Coffee Shack"))
        self.lblRaminsCoffeeShack.setText(_translate("raminsCoffeeShack", "Ramin\'s Coffee Shack"))
        self.lblNumberofLattes.setText(_translate("raminsCoffeeShack", "Number of Lattes"))
        self.lblNumberofCappuccinos.setText(_translate("raminsCoffeeShack", "Number Of Cappuccinos"))
        self.label_3.setText(_translate("raminsCoffeeShack", "Number of Espressos"))
        self.lblSize.setText(_translate("raminsCoffeeShack", "Size"))
        self.lblLatteCost.setText(_translate("raminsCoffeeShack", "$4.50"))
        self.lblListofSize.setText(_translate("raminsCoffeeShack", "Small or Large"))
        self.lblEspressoCost.setText(_translate("raminsCoffeeShack", "$5.50"))
        self.lblCappuccinoCost.setText(_translate("raminsCoffeeShack", "$5.00"))
        self.lblTip.setText(_translate("raminsCoffeeShack", "Add a Tip? (optional)"))
        self.btnSubmitOrder.setText(_translate("raminsCoffeeShack", "Submit Order"))
        self.lblTotalCost.setText(_translate("raminsCoffeeShack", "Total:"))
        self.lblDollarSign.setText(_translate("raminsCoffeeShack", "$"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    raminsCoffeeShack = QtWidgets.QMainWindow()
    ui = Ui_raminsCoffeeShack()
    ui.setupUi(raminsCoffeeShack)
    raminsCoffeeShack.show()
    sys.exit(app.exec())
