# Form implementation generated from reading ui file 'gymMembershipCalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_gymMembershipCalculator(object):
    def setupUi(self, gymMembershipCalculator):
        gymMembershipCalculator.setObjectName("gymMembershipCalculator")
        gymMembershipCalculator.resize(874, 682)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        gymMembershipCalculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=gymMembershipCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.lblLastName.setObjectName("lblLastName")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.lblFirstName.setObjectName("lblFirstName")
        self.lblAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAge.setGeometry(QtCore.QRect(10, 140, 131, 16))
        self.lblAge.setObjectName("lblAge")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.txtFirstName.setObjectName("txtFirstName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(140, 110, 113, 20))
        self.txtLastName.setObjectName("txtLastName")
        self.txtAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAge.setGeometry(QtCore.QRect(140, 140, 113, 20))
        self.txtAge.setObjectName("txtAge")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(10, 240, 91, 16))
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(140, 240, 111, 22))
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.lblStudentQuestion = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentQuestion.setGeometry(QtCore.QRect(10, 340, 121, 16))
        self.lblStudentQuestion.setObjectName("lblStudentQuestion")
        self.chbYes = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chbYes.setGeometry(QtCore.QRect(150, 340, 70, 17))
        self.chbYes.setObjectName("chbYes")
        self.chbNo = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chbNo.setGeometry(QtCore.QRect(250, 340, 70, 17))
        self.chbNo.setObjectName("chbNo")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(90, 450, 101, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblFirstMonthFee = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstMonthFee.setGeometry(QtCore.QRect(20, 490, 111, 16))
        self.lblFirstMonthFee.setObjectName("lblFirstMonthFee")
        self.lblMonthlyFee = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMonthlyFee.setGeometry(QtCore.QRect(20, 520, 111, 16))
        self.lblMonthlyFee.setObjectName("lblMonthlyFee")
        self.txtFirstMonthFee = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstMonthFee.setGeometry(QtCore.QRect(140, 490, 113, 20))
        self.txtFirstMonthFee.setReadOnly(True)
        self.txtFirstMonthFee.setObjectName("txtFirstMonthFee")
        self.txtMonthlyFee = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMonthlyFee.setGeometry(QtCore.QRect(140, 520, 113, 20))
        self.txtMonthlyFee.setReadOnly(True)
        self.txtMonthlyFee.setObjectName("txtMonthlyFee")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(790, 610, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(10, 610, 75, 23))
        self.btnClear.setObjectName("btnClear")
        gymMembershipCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gymMembershipCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 22))
        self.menubar.setObjectName("menubar")
        gymMembershipCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gymMembershipCalculator)
        self.statusbar.setObjectName("statusbar")
        gymMembershipCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(gymMembershipCalculator)
        QtCore.QMetaObject.connectSlotsByName(gymMembershipCalculator)
        
        # This is where I establish the fees and discount which I will call upon later
        self.plan_fees = {"Basic": 30, "Standard": 45, "Premium": 60, "Family": 80}
        self.facility_fee = 20
        self.student_discount_rate = 0.20
        
        # This connects the buttons to the functions below
        self.btnCalculate.clicked.connect(self.calculate_fee)
        self.btnClear.clicked.connect(self.clear_form)
        self.btnExit.clicked.connect(self.exit_app)
        
        
    def calculate_fee(self):
        # This will show an error message if no information is put in the boxes
        if self.txtFirstName.text() == "" or self.txtLastName.text() == "" or self.txtAge.text() == "":
            msg = QMessageBox()
            msg.setText("Please fill all fields")
            msg.exec()
        else:
            # This reads the inputs
            plan = self.cmbPlan.currentText()
            is_student = self.chbYes.isChecked()

            # This is the fee before discounts or first month fees
            base = self.plan_fees.get(plan, 0)

            # This is where the discount is set
            if is_student:
                discount = self.student_discount_rate * base
            else:
                discount = 0

            # This is where everything is being calculated
            monthly_after = base - discount
            first_month = monthly_after + self.facility_fee

            # This displays the result
            self.txtFirstMonthFee.setText(f"${first_month:.2f}")
            self.txtMonthlyFee.setText(f"${monthly_after:.2f}")
        
    # This clears the form  
    def clear_form(self):
        self.txtFirstName.clear()
        self.txtLastName.clear()
        self.txtAge.clear()
        self.cmbPlan.setCurrentIndex(0)  # Basic
        self.chbYes.setChecked(False)
        self.chbNo.setChecked(False)
        self.txtFirstMonthFee.clear()
        self.txtMonthlyFee.clear()
    
    # This exits the app
    def exit_app(self):
        QtWidgets.QApplication.quit()


    def retranslateUi(self, gymMembershipCalculator):
        _translate = QtCore.QCoreApplication.translate
        gymMembershipCalculator.setWindowTitle(_translate("gymMembershipCalculator", "Gym Membership Calculator"))
        self.lblLastName.setText(_translate("gymMembershipCalculator", "Enter last name"))
        self.lblFirstName.setText(_translate("gymMembershipCalculator", "Enter first name"))
        self.lblAge.setText(_translate("gymMembershipCalculator", "Enter Age"))
        self.lblPlan.setText(_translate("gymMembershipCalculator", "Choose plan"))
        self.cmbPlan.setItemText(0, _translate("gymMembershipCalculator", "Basic"))
        self.cmbPlan.setItemText(1, _translate("gymMembershipCalculator", "Standard"))
        self.cmbPlan.setItemText(2, _translate("gymMembershipCalculator", "Premium"))
        self.cmbPlan.setItemText(3, _translate("gymMembershipCalculator", "Family"))
        self.lblStudentQuestion.setText(_translate("gymMembershipCalculator", "Are you a student?"))
        self.chbYes.setText(_translate("gymMembershipCalculator", "Yes"))
        self.chbNo.setText(_translate("gymMembershipCalculator", "No"))
        self.btnCalculate.setText(_translate("gymMembershipCalculator", "Calculate Cost"))
        self.lblFirstMonthFee.setText(_translate("gymMembershipCalculator", "First month fee:"))
        self.lblMonthlyFee.setText(_translate("gymMembershipCalculator", "Monthly Fee:"))
        self.btnExit.setText(_translate("gymMembershipCalculator", "Exit"))
        self.btnClear.setText(_translate("gymMembershipCalculator", "Clear Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gymMembershipCalculator = QtWidgets.QMainWindow()
    ui = Ui_gymMembershipCalculator()
    ui.setupUi(gymMembershipCalculator)
    gymMembershipCalculator.show()
    sys.exit(app.exec())
