# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6 import QtWidgets
from purchaseWindow import Ui_purchaseWindow
from searchWindow import Ui_searchWindow
from displayWindow import Ui_displayWindow

class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(1042, 740)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dashboard.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(290, 140, 81, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(380, 140, 113, 20))
        self.txtName.setObjectName("txtName")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(170, 30, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchase.setGeometry(QtCore.QRect(190, 240, 75, 23))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(340, 240, 75, 23))
        self.btnSearch.setObjectName("btnSearch")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(500, 240, 75, 23))
        self.btnDisplay.setObjectName("btnDisplay")
        dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 22))
        self.menubar.setObjectName("menubar")
        dashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)
        
        self.btnPurchase.clicked.connect(self.open_purchase_window)
        self.btnSearch.clicked.connect(self.open_search_window)
        self.btnDisplay.clicked.connect(self.open_display_window)
        self.btnExit.clicked.connect(QtWidgets.QApplication.quit)
    
    # Function to open purchase window
    def open_purchase_window(self):
        self.window = QtWidgets.QMainWindow()
        self.purchaseui = Ui_purchaseWindow()
        self.purchaseui.setupUi(self.window, parent=self)
        self.window.show()
            
    # Function to open search window
    def open_search_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_searchWindow()
        self.ui.setupUi(self.window)
        self.ui.customer_name = self.txtName.text()
        self.window.show()
        
    # Function to open display window
    def open_display_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_displayWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Dashboard"))
        self.lblName.setText(_translate("dashboard", "Enter Name:"))
        self.btnExit.setText(_translate("dashboard", "Exit"))
        self.btnPurchase.setText(_translate("dashboard", "Purchase"))
        self.btnSearch.setText(_translate("dashboard", "Search"))
        self.btnDisplay.setText(_translate("dashboard", "Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard = QtWidgets.QMainWindow()
    ui = Ui_dashboard()
    ui.setupUi(dashboard)
    dashboard.show()
    sys.exit(app.exec())
