# Form implementation generated from reading ui file 'searchWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_searchWindow(object):
    def setupUi(self, searchWindow):
        searchWindow.setObjectName("searchWindow")
        searchWindow.resize(910, 693)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        searchWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=searchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFindAveragePrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFindAveragePrice.setGeometry(QtCore.QRect(150, 100, 131, 16))
        self.lblFindAveragePrice.setObjectName("lblFindAveragePrice")
        self.cmbTicketTypePrice = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbTicketTypePrice.setGeometry(QtCore.QRect(460, 100, 121, 22))
        self.cmbTicketTypePrice.setObjectName("cmbTicketTypePrice")
        self.cmbTicketTypePrice.addItem("")
        self.cmbTicketTypePrice.addItem("")
        self.cmbTicketTypePrice.addItem("")
        self.cmbTicketTypePrice.addItem("")
        self.lblAverageTicketTypePrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAverageTicketTypePrice.setGeometry(QtCore.QRect(150, 180, 71, 16))
        self.lblAverageTicketTypePrice.setObjectName("lblAverageTicketTypePrice")
        self.txtAverageTicketTypePrice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAverageTicketTypePrice.setGeometry(QtCore.QRect(460, 180, 113, 20))
        self.txtAverageTicketTypePrice.setReadOnly(True)
        self.txtAverageTicketTypePrice.setObjectName("txtAverageTicketTypePrice")
        self.lblTicketTypeTransactions = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTicketTypeTransactions.setGeometry(QtCore.QRect(150, 270, 241, 16))
        self.lblTicketTypeTransactions.setObjectName("lblTicketTypeTransactions")
        self.tblTransactions = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblTransactions.setGeometry(QtCore.QRect(460, 270, 371, 311))
        self.tblTransactions.setObjectName("tblTransactions")
        self.tblTransactions.setColumnCount(5)
        self.tblTransactions.setHorizontalHeaderLabels(["Transaction ID", "Ticket Type", "Quantity", "Total", "Customer Name"])
        self.tblTransactions.setRowCount(0)
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(320, 220, 75, 23))
        self.btnSearch.setObjectName("btnSearch")
        searchWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=searchWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 21))
        self.menubar.setObjectName("menubar")
        searchWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=searchWindow)
        self.statusbar.setObjectName("statusbar")
        searchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(searchWindow)
        QtCore.QMetaObject.connectSlotsByName(searchWindow)

        self.btnSearch.clicked.connect(self.search_transactions)
        self.customer_name = ""
    
    # Searches transactions and displays when the ticket type matches what is in the combo box
    def search_transactions(self):
        try:
            self.tblTransactions.clearContents()
            self.tblTransactions.setRowCount(0)

            tickettype = self.cmbTicketTypePrice.currentText()
            name = self.customer_name   

            connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="finalprojectdb")

            cursor = connection.cursor()

            cursor.execute("SELECT transactionid, tickettype, quantity, total, customername " "FROM fair_ticket_sales WHERE customername = %s", [name])
            customer_rows = cursor.fetchall()

            for row in customer_rows:
                row_position = self.tblTransactions.rowCount()
                self.tblTransactions.insertRow(row_position)
                for col_index, col_data in enumerate(row):
                    self.tblTransactions.setItem(row_position, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

            cursor.execute("SELECT transactionid, tickettype, quantity, total, customername " "FROM fair_ticket_sales WHERE tickettype = %s",[tickettype])
            type_rows = cursor.fetchall()

            for row in type_rows:
                row_position = self.tblTransactions.rowCount()
                self.tblTransactions.insertRow(row_position)
                for col_index, col_data in enumerate(row):
                    self.tblTransactions.setItem(row_position, col_index, QtWidgets.QTableWidgetItem(str(col_data)))

            cursor.execute("SELECT AVG(total) FROM fair_ticket_sales WHERE tickettype = %s", [tickettype])
            avg_value = cursor.fetchone()[0]

            if avg_value is None:
                avg_value = 0

            self.txtAverageTicketTypePrice.setText(str(round(avg_value, 2)))

        except Exception as e:
            print(e)

        finally:
            try:
                if(connection):
                    connection.close()
            except:
                pass


    def retranslateUi(self, searchWindow):
        _translate = QtCore.QCoreApplication.translate
        searchWindow.setWindowTitle(_translate("searchWindow", "Search Window"))
        self.lblFindAveragePrice.setText(_translate("searchWindow", "Find Average Price of:"))
        self.cmbTicketTypePrice.setItemText(0, _translate("searchWindow", "Adult Ticket"))
        self.cmbTicketTypePrice.setItemText(1, _translate("searchWindow", "Child Ticket"))
        self.cmbTicketTypePrice.setItemText(2, _translate("searchWindow", "Student Ticket"))
        self.cmbTicketTypePrice.setItemText(3, _translate("searchWindow", "Ride Pass"))
        self.lblAverageTicketTypePrice.setText(_translate("searchWindow", "Average:"))
        self.lblTicketTypeTransactions.setText(_translate("searchWindow", "Transactions With Same Ticket Type:"))
        self.btnSearch.setText(_translate("searchWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchWindow = QtWidgets.QMainWindow()
    ui = Ui_searchWindow()
    ui.setupUi(searchWindow)
    searchWindow.show()
    sys.exit(app.exec())
