# Form implementation generated from reading ui file 'gradeCalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_gradeCalculator(object):
    def setupUi(self, gradeCalculator):
        gradeCalculator.setObjectName("gradeCalculator")
        gradeCalculator.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        gradeCalculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=gradeCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(330, 100, 141, 16))
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(490, 100, 113, 20))
        self.txtScore.setObjectName("txtScore")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(490, 140, 121, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(330, 240, 91, 16))
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(490, 240, 113, 20))
        self.txtGrade.setReadOnly(True)
        self.txtGrade.setObjectName("txtGrade")
        gradeCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gradeCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        gradeCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gradeCalculator)
        self.statusbar.setObjectName("statusbar")
        gradeCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(gradeCalculator)
        QtCore.QMetaObject.connectSlotsByName(gradeCalculator)
        
        self.btnCalculate.clicked.connect(self.calculate_grade)
        
        
    def calculate_grade(self):
        # Get the current value enetered by the user and store the value in the variable input_value
        
        input_value = self.txtScore.text()
        # input validation to ensure value enetered is an integer
        if(input_value.isdigit()):
            # transform the input value to an integer (value is a string so has to be transformed)
            student_score = int(input_value)
            # input validation to ensure score enetered is between 0 and 100
            if(student_score >=0 and student_score <= 100):
                # grade calculation block to assign grade
                if(student_score >=90):
                    grade = "A"
                elif(student_score >= 80):
                    grade = "B"
                elif(student_score >= 70):
                    grade = "C"
                elif(student_score >= 60):
                    grade = "D"
                else:
                    grade = "F"
                self.txtGrade.setText(grade)
            else:
                # Error message to display when value enetered is not between 0 and 100
                msg = QMessageBox()
                msg.setText("Please enter a score between 0 and 100")
                msg.exec()
        else:
            # Error message to display to display when value enetered is not an integer
            msg = QMessageBox()
            msg.setText("Please enter a numeric score")
            msg.exec()
                

    def retranslateUi(self, gradeCalculator):
        _translate = QtCore.QCoreApplication.translate
        gradeCalculator.setWindowTitle(_translate("gradeCalculator", "Grade Calculator"))
        self.lblScore.setText(_translate("gradeCalculator", "Enter student score"))
        self.btnCalculate.setText(_translate("gradeCalculator", "Calculate Grade"))
        self.lblGrade.setText(_translate("gradeCalculator", "Student grade"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gradeCalculator = QtWidgets.QMainWindow()
    ui = Ui_gradeCalculator()
    ui.setupUi(gradeCalculator)
    gradeCalculator.show()
    sys.exit(app.exec())
