# Form implementation generated from reading ui file 'financialPlanner2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner2(object):
    def setupUi(self, financialPlanner2):
        financialPlanner2.setObjectName("financialPlanner2")
        financialPlanner2.resize(1093, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        financialPlanner2.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner2)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAmount.setGeometry(QtCore.QRect(50, 70, 171, 16))
        self.lblAmount.setObjectName("lblAmount")
        self.txtAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAmount.setGeometry(QtCore.QRect(370, 70, 113, 20))
        self.txtAmount.setObjectName("txtAmount")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(50, 120, 171, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(370, 120, 113, 20))
        self.txtTime.setObjectName("txtTime")
        self.chkRate = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkRate.setGeometry(QtCore.QRect(370, 170, 70, 17))
        self.chkRate.setObjectName("chkRate")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(50, 270, 75, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(350, 270, 75, 23))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(630, 270, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(790, 50, 256, 361))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(820, 30, 191, 16))
        self.lblOutput.setObjectName("lblOutput")
        financialPlanner2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 22))
        self.menubar.setObjectName("menubar")
        financialPlanner2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner2)
        self.statusbar.setObjectName("statusbar")
        financialPlanner2.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner2)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner2)
        
        # When the calculate button is clicked, cal the calculate_portfolio_balance function
        self.btnCalculate.clicked.connect(self.calculate_portfolio_balance)
        
        self.btnClear.clicked.connect(self.clear_application)
        
        self.btnExit.clicked.connect(self.exit_application)
        
    def exit_application(self):
        QtWidgets.QApplication.quit()
        
        
    def clear_application(self):
        # Clear the annual deposit amount line edit widget
        self.txtAmount.clear()
        # Clear the number of year to invest line edit widget
        self.txtTime.clear()
        # Uncheck the check box
        self.chkRate.setChecked(False)
        # Clear the list widget
        self.lstOutput.clear()
        
    def calculate_portfolio_balance(self):
        # Get the user input for the annual investment amount
        annual_amount = int(self.txtAmount.text())
        # Get the user input for total number of years
        number_of_years = int(self.txtTime.text())
        
        # Evaluate if the check box is selected. If check box is selected, rate = 7.0 else rate = 5.0
        if(self.chkRate.isChecked()):
            rate = 7.0
        else:
            rate = 5.0
            
        # print(rate)
            
        # Setting initial portfolio balance to 0
        initial_amount = 0
        
        # Adding column headers to the list widget
        self.lstOutput.addItem(f"Time      Portfolio Balance")
        
        # Calculate portfolio balance at the end of each year
        for time in range(1, number_of_years + 1):
            initial_amount = (initial_amount + annual_amount)*(1 + rate/100)
            # self.lstOutput.addItem(str(time)+ " " +str(initial_amount))
            # Display the year and portfolio balance at the end of each year
            self.lstOutput.addItem(f"{time}          ${initial_amount:.2f}")
            

    def retranslateUi(self, financialPlanner2):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner2.setWindowTitle(_translate("financialPlanner2", "Financial Planner 2"))
        self.lblAmount.setText(_translate("financialPlanner2", "Enter annual deposit amount"))
        self.lblTime.setText(_translate("financialPlanner2", "Number of years to invest"))
        self.chkRate.setText(_translate("financialPlanner2", "High risk"))
        self.btnCalculate.setText(_translate("financialPlanner2", "Calculate"))
        self.btnClear.setText(_translate("financialPlanner2", "Clear"))
        self.btnExit.setText(_translate("financialPlanner2", "Exit"))
        self.lblOutput.setText(_translate("financialPlanner2", "Portfolio balance after each year"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner2 = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner2()
    ui.setupUi(financialPlanner2)
    financialPlanner2.show()
    sys.exit(app.exec())
