# Form implementation generated from reading ui file 'displayWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_displayWindow(object):
    def setupUi(self, displayWindow):
        displayWindow.setObjectName("displayWindow")
        displayWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        displayWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=displayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnDisplayTransactions = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplayTransactions.setGeometry(QtCore.QRect(330, 60, 75, 23))
        self.btnDisplayTransactions.setObjectName("btnDisplayTransactions")
        self.tblDisplayedTransactions = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblDisplayedTransactions.setGeometry(QtCore.QRect(170, 120, 421, 341))
        self.tblDisplayedTransactions.setObjectName("tblDisplayedTransactions")
        self.tblDisplayedTransactions.setColumnCount(0)
        self.tblDisplayedTransactions.setRowCount(0)
        displayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=displayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        displayWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=displayWindow)
        self.statusbar.setObjectName("statusbar")
        displayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(displayWindow)
        QtCore.QMetaObject.connectSlotsByName(displayWindow)

        self.btnDisplayTransactions.clicked.connect(self.display_all_transactions)

    # Displays all the transactions 
    def display_all_transactions(self):
        try:
            self.tblDisplayedTransactions.clearContents()
            self.tblDisplayedTransactions.setRowCount(0)

            connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="finalprojectdb")

            cursor = connection.cursor()

            cursor.execute("SELECT transactionid, customername, tickettype, quantity, total FROM fair_ticket_sales")
            data = cursor.fetchall()

            headers = ["Transaction ID", "Customer Name", "Ticket Type", "Quantity", "Total"]
            self.tblDisplayedTransactions.setColumnCount(5)
            self.tblDisplayedTransactions.setHorizontalHeaderLabels(headers)

            row_count = len(data)
            self.tblDisplayedTransactions.setRowCount(row_count)

            for row_number, row_data in enumerate(data):
                for column_number, column_data in enumerate(row_data):
                    self.tblDisplayedTransactions.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(column_data)))

        except Exception as e:
            print(e)

        finally:
            try:
                if(connection):
                    connection.close()
            except:
                pass   
        
        
        
    def retranslateUi(self, displayWindow):
        _translate = QtCore.QCoreApplication.translate
        displayWindow.setWindowTitle(_translate("displayWindow", "Display Window"))
        self.btnDisplayTransactions.setText(_translate("displayWindow", "Display"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    displayWindow = QtWidgets.QMainWindow()
    ui = Ui_displayWindow()
    ui.setupUi(displayWindow)
    displayWindow.show()
    sys.exit(app.exec())
