# Form implementation generated from reading ui file 'purchaseWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import pymysql as mdb

class Ui_purchaseWindow(object):
    def setupUi(self, purchaseWindow, parent=None):
        self.parent = parent
        purchaseWindow.setObjectName("purchaseWindow")
        purchaseWindow.resize(1067, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        purchaseWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=purchaseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTransactionId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTransactionId.setGeometry(QtCore.QRect(280, 150, 131, 16))
        self.lblTransactionId.setObjectName("lblTransactionId")
        self.txtTransactionId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTransactionId.setGeometry(QtCore.QRect(430, 150, 113, 20))
        self.txtTransactionId.setObjectName("txtTransactionId")
        self.lblTicketType = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTicketType.setGeometry(QtCore.QRect(280, 190, 121, 16))
        self.lblTicketType.setObjectName("lblTicketType")
        self.cmbTicketType = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbTicketType.setGeometry(QtCore.QRect(430, 190, 111, 22))
        self.cmbTicketType.setObjectName("cmbTicketType")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(280, 230, 111, 16))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(430, 230, 113, 20))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(370, 290, 75, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblSubTotal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblSubTotal.setGeometry(QtCore.QRect(280, 340, 71, 16))
        self.lblSubTotal.setObjectName("lblSubTotal")
        self.lblTotal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotal.setGeometry(QtCore.QRect(280, 370, 111, 16))
        self.lblTotal.setObjectName("lblTotal")
        self.txtSubTotal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSubTotal.setGeometry(QtCore.QRect(430, 340, 113, 20))
        self.txtSubTotal.setReadOnly(True)
        self.txtSubTotal.setObjectName("txtSubTotal")
        self.txtTotal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotal.setGeometry(QtCore.QRect(430, 370, 113, 20))
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchase.setGeometry(QtCore.QRect(370, 410, 75, 23))
        self.btnPurchase.setObjectName("btnPurchase")
        purchaseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=purchaseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 21))
        self.menubar.setObjectName("menubar")
        purchaseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=purchaseWindow)
        self.statusbar.setObjectName("statusbar")
        purchaseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(purchaseWindow)
        QtCore.QMetaObject.connectSlotsByName(purchaseWindow)
        
        self.btnCalculate.clicked.connect(self.calculate_total)
        self.btnPurchase.clicked.connect(self.purchase_ticket)
        
        self.price_data = {}
        
        self.load_price_data("ticketPrices.txt")
        
    # Load prices from the text file     
    def load_price_data(self, filename):
        try:
            with open(filename, "r") as f:
                for line in f:
                    data = line.split(",")
                    ticket = data[0].strip()
                    price = int(data[1].strip())
                    self.price_data[ticket] = price

        except FileNotFoundError:
            print("The file could not be opened")
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
            
    # Calculations         
    def calculate_total(self):
        try:
            ticket = self.cmbTicketType.currentText()
            quantity = int(self.txtQuantity.text())
            price = self.price_data[ticket]

            subtotal = price * quantity
            total = subtotal * 1.08 

            self.txtSubTotal.setText(str(subtotal))
            self.txtTotal.setText(str(round(total, 2)))

        except Exception as e:
            print(e)
            msg = QMessageBox()
            msg.setText("Please enter a valid quantity.")
            msg.exec()

    # Inserts purchase into database
    def purchase_ticket(self):
        try:
            transactionid = int(self.txtTransactionId.text())
            ticket = self.cmbTicketType.currentText()
            quantity = int(self.txtQuantity.text())
            total = float(self.txtTotal.text())
            customername = self.parent.txtName.text()

            connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="finalprojectdb")

            cursor = connection.cursor()

            cursor.execute("INSERT INTO fair_ticket_sales(transactionid, customername, tickettype, quantity, total) VALUES(%s, %s, %s, %s, %s)", [transactionid, customername, ticket, quantity, total])
        
            connection.commit()
            print("Data added")

            msg = QMessageBox()
            msg.setText("Purchase completed successfully.")
            msg.exec()

        except Exception as e:
            print(e)
            msg = QMessageBox()
            msg.setText("Error: Could not complete purchase.")
            msg.exec()

        finally:
            try:
                if(connection):
                    connection.close()
            except:
                pass
    
    def retranslateUi(self, purchaseWindow):
        _translate = QtCore.QCoreApplication.translate
        purchaseWindow.setWindowTitle(_translate("purchaseWindow", "Purchase Window"))
        self.lblTransactionId.setText(_translate("purchaseWindow", "Enter Transaction ID:"))
        self.lblTicketType.setText(_translate("purchaseWindow", "Select Ticket Type:"))
        self.cmbTicketType.setItemText(0, _translate("purchaseWindow", "Adult Ticket"))
        self.cmbTicketType.setItemText(1, _translate("purchaseWindow", "Child Ticket"))
        self.cmbTicketType.setItemText(2, _translate("purchaseWindow", "Student Ticket"))
        self.cmbTicketType.setItemText(3, _translate("purchaseWindow", "Ride Pass"))
        self.lblQuantity.setText(_translate("purchaseWindow", "Enter Quantity:"))
        self.btnCalculate.setText(_translate("purchaseWindow", "Calculate"))
        self.lblSubTotal.setText(_translate("purchaseWindow", "Sub Total:"))
        self.lblTotal.setText(_translate("purchaseWindow", "Total After Taxes:"))
        self.btnPurchase.setText(_translate("purchaseWindow", "Purchase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_purchaseWindow()
    ui.setupUi(window)     
    window.show()
    sys.exit(app.exec())
