# Form implementation generated from reading ui file 'studentGradeManagementApplication.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb
from PyQt6.QtWidgets import QMessageBox

class Ui_studentGradeManagementApplication(object):
    def setupUi(self, studentGradeManagementApplication):
        studentGradeManagementApplication.setObjectName("studentGradeManagementApplication")
        studentGradeManagementApplication.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentGradeManagementApplication.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentGradeManagementApplication)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 771, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lblStudentId = QtWidgets.QLabel(parent=self.tab)
        self.lblStudentId.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.lblStudentId.setObjectName("lblStudentId")
        self.lblStudentName = QtWidgets.QLabel(parent=self.tab)
        self.lblStudentName.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.lblStudentName.setObjectName("lblStudentName")
        self.lblStudentScore = QtWidgets.QLabel(parent=self.tab)
        self.lblStudentScore.setGeometry(QtCore.QRect(10, 110, 151, 16))
        self.lblStudentScore.setObjectName("lblStudentScore")
        self.txtId = QtWidgets.QLineEdit(parent=self.tab)
        self.txtId.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.txtId.setObjectName("txtId")
        self.txtName = QtWidgets.QLineEdit(parent=self.tab)
        self.txtName.setGeometry(QtCore.QRect(180, 70, 113, 20))
        self.txtName.setObjectName("txtName")
        self.txtScore = QtWidgets.QLineEdit(parent=self.tab)
        self.txtScore.setGeometry(QtCore.QRect(180, 110, 113, 20))
        self.txtScore.setObjectName("txtScore")
        self.btnInsert = QtWidgets.QPushButton(parent=self.tab)
        self.btnInsert.setGeometry(QtCore.QRect(10, 170, 111, 23))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.tab)
        self.btnDisplay.setGeometry(QtCore.QRect(160, 170, 111, 23))
        self.btnDisplay.setObjectName("btnDisplay")
        self.tblStudentData = QtWidgets.QTableWidget(parent=self.tab)
        self.tblStudentData.setGeometry(QtCore.QRect(20, 270, 256, 192))
        self.tblStudentData.setObjectName("tblStudentData")
        self.tblStudentData.setColumnCount(0)
        self.tblStudentData.setRowCount(0)
        self.lblStudentData = QtWidgets.QLabel(parent=self.tab)
        self.lblStudentData.setGeometry(QtCore.QRect(100, 240, 81, 16))
        self.lblStudentData.setObjectName("lblStudentData")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listStudentData = QtWidgets.QListWidget(parent=self.tab_2)
        self.listStudentData.setGeometry(QtCore.QRect(20, 10, 711, 241))
        self.listStudentData.setObjectName("listStudentData")
        self.btnExport = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnExport.setGeometry(QtCore.QRect(320, 310, 91, 23))
        self.btnExport.setObjectName("btnExport")
        self.tabWidget.addTab(self.tab_2, "")
        studentGradeManagementApplication.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentGradeManagementApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        studentGradeManagementApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentGradeManagementApplication)
        self.statusbar.setObjectName("statusbar")
        studentGradeManagementApplication.setStatusBar(self.statusbar)

        self.retranslateUi(studentGradeManagementApplication)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(studentGradeManagementApplication)
        
        # self.load_data("student_data.txt")
        self.btnInsert.clicked.connect(self.insert_data)
        self.btnDisplay.clicked.connect(self.display_data)
        self.btnExport.clicked.connect(self.export_data)
        self.tabWidget.currentChanged.connect(self.load_grades)
        
    # This function was to load in the data the first time however it was causing duplicates and so I made it a comment   
    def load_data(self, filename):
        try:
            connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="project4db")
            cursor = connection.cursor()

            with open(filename, "r") as fname:
                for line in fname:
                    data = line.split(",")
                    cursor.execute("INSERT INTO student (studentid, studentname, studentscore) VALUES (%s, %s, %s)",[data[0].strip(), data[1].strip(), data[2].strip()])
                    connection.commit()

        except Exception as e:
            print(e)
        finally:
            if(connection):
                connection.close()
                
                
                
    # This function is for when you click the display button in the application            
    def display_data(self):
        try:
            # Connect to the databse
            connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="project4db")
            cursor = connection.cursor()
            # Retrieve the data
            cursor.execute("select * from student")
            data = cursor.fetchall()
            # Formatting the data with rows and columns
            row_count = len(data)
            column_count = len(cursor.description)
            headers = ["Student ID", "Student Name", "Student Score"]
            self.tblStudentData.setRowCount(row_count)
            self.tblStudentData.setColumnCount(column_count)    
            self.tblStudentData.setHorizontalHeaderLabels(headers)
            # Fill the table widget
            for row_number, row_data in enumerate(data):
                for column_number, column_data in enumerate(row_data):
                    self.tblStudentData.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(f"{column_data}"))
        
        except Exception as e:
            print(e)
        finally:
            if(connection):
                connection.close()
                
                
                
    # This function is for when you click the insert button in the application            
    def insert_data(self):
        try:
            # Reads the values from the line edits
            sid = int(self.txtId.text())
            sname = self.txtName.text()
            sscore = int(self.txtScore.text())
            # Connect to data base
            dbconnection = mdb.connect(host="localhost", port=3306, database="project4db", user="442user", password="442user")
            # If there is a connection to database then insert the new data
            if(dbconnection):
                cursor = dbconnection.cursor()
                cursor.execute("INSERT INTO student(studentid, studentname, studentscore) VALUES (%s, %s, %s)",[sid, sname, sscore])
                dbconnection.commit()
                print("Data added")
            else:
                print("DB connection failed")
        except Exception as e:
            print(e)
        finally:
            if(dbconnection):
                dbconnection.close()
                
                
                
                
    # This function is for when you click the export button on the student grades tab            
    def export_data(self):
        try:
            # Makes a text file to export the data to
            f = open("studentgrades.txt", "w")
            # Write the data from list widget into the text file
            for i in range(self.listStudentData.count()):
                f.write(self.listStudentData.item(i).text() + "\n")
            # Closes the text file
            f.close()
            # Confirms the export in cmd
            print("Data exported")

        except Exception as e:
            print(e)
            
            
            
    # This function is for when you click on the student grades tab        
    def load_grades(self):
        try:
            # Makes sure to run when the students grade tab is selected
            if(self.tabWidget.currentIndex() == 1):
                # Clears the list before loading data
                self.listStudentData.clear()
                # Connects to the database
                connection = mdb.connect(host="localhost", port=3306, user="442user", password="442user", database="project4db")
                cursor = connection.cursor()
                # Retreives student data from database
                cursor.execute("select * from student")
                data = cursor.fetchall()
                # Closes the connection
                connection.close()
                # This is the part where letter grades are assigned to scores
                for item in data:
                    score = int(item[2])

                    if score < 60:
                        grade = "F"
                    elif score < 70:
                        grade = "D"
                    elif score < 80:
                        grade = "C"
                    elif score < 90:
                        grade = "B"
                    else:
                        grade = "A"
                    # Formatting so everything is not bunched up and very neat
                    line = f"{item[0]}     {item[1]}     {grade}"
                    self.listStudentData.addItem(line)
            else:
                self.listStudentData.clear()

        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
        

    def retranslateUi(self, studentGradeManagementApplication):
        _translate = QtCore.QCoreApplication.translate
        studentGradeManagementApplication.setWindowTitle(_translate("studentGradeManagementApplication", "Student grade Management Application"))
        self.lblStudentId.setText(_translate("studentGradeManagementApplication", "Enter Student ID:"))
        self.lblStudentName.setText(_translate("studentGradeManagementApplication", "Enter Student Name:"))
        self.lblStudentScore.setText(_translate("studentGradeManagementApplication", "Enter Student Score:"))
        self.btnInsert.setText(_translate("studentGradeManagementApplication", "Insert Data"))
        self.btnDisplay.setText(_translate("studentGradeManagementApplication", "Display Data"))
        self.lblStudentData.setText(_translate("studentGradeManagementApplication", "Student Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("studentGradeManagementApplication", "Student Info"))
        self.btnExport.setText(_translate("studentGradeManagementApplication", "Export Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("studentGradeManagementApplication", "Student Grade"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentGradeManagementApplication = QtWidgets.QMainWindow()
    ui = Ui_studentGradeManagementApplication()
    ui.setupUi(studentGradeManagementApplication)
    studentGradeManagementApplication.show()
    sys.exit(app.exec())
