# Form implementation generated from reading ui file 'homePurchaseApplication.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QMessageBox


class Ui_homePurchaseApplication(object):
    def setupUi(self, homePurchaseApplication):
        homePurchaseApplication.setObjectName("homePurchaseApplication")
        homePurchaseApplication.resize(1367, 975)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        homePurchaseApplication.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=homePurchaseApplication)
        self.centralwidget.setObjectName("centralwidget")
        self.tbHomePurchaseApplication = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbHomePurchaseApplication.setGeometry(QtCore.QRect(20, 10, 1321, 921))
        self.tbHomePurchaseApplication.setObjectName("tbHomePurchaseApplication")
        self.tbPurchase = QtWidgets.QWidget()
        self.tbPurchase.setObjectName("tbPurchase")
        self.lblCustomerName = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblCustomerName.setGeometry(QtCore.QRect(60, 110, 91, 16))
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.tbPurchase)
        self.txtCustomerName.setGeometry(QtCore.QRect(140, 110, 113, 20))
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.lblCustomerAge = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblCustomerAge.setGeometry(QtCore.QRect(60, 140, 71, 16))
        self.lblCustomerAge.setObjectName("lblCustomerAge")
        self.lblCustomerInfo = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblCustomerInfo.setGeometry(QtCore.QRect(130, 70, 91, 16))
        self.lblCustomerInfo.setObjectName("lblCustomerInfo")
        self.txtCustomerAge = QtWidgets.QLineEdit(parent=self.tbPurchase)
        self.txtCustomerAge.setGeometry(QtCore.QRect(140, 140, 113, 20))
        self.txtCustomerAge.setObjectName("txtCustomerAge")
        self.lblHouse = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblHouse.setGeometry(QtCore.QRect(410, 70, 47, 13))
        self.lblHouse.setObjectName("lblHouse")
        self.cmbHouseType = QtWidgets.QComboBox(parent=self.tbPurchase)
        self.cmbHouseType.setGeometry(QtCore.QRect(450, 110, 151, 22))
        self.cmbHouseType.setObjectName("cmbHouseType")
        self.cmbHouseType.addItem("")
        self.cmbHouseType.addItem("")
        self.cmbHouseType.addItem("")
        self.cmbHouseType.addItem("")
        self.lblHouseType = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblHouseType.setGeometry(QtCore.QRect(350, 110, 81, 16))
        self.lblHouseType.setObjectName("lblHouseType")
        self.lblModel = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblModel.setGeometry(QtCore.QRect(730, 70, 47, 13))
        self.lblModel.setObjectName("lblModel")
        self.grpModelType = QtWidgets.QGroupBox(parent=self.tbPurchase)
        self.grpModelType.setGeometry(QtCore.QRect(690, 100, 171, 131))
        self.grpModelType.setObjectName("grpModelType")
        self.rdbStandard = QtWidgets.QRadioButton(parent=self.grpModelType)
        self.rdbStandard.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.rdbStandard.setObjectName("rdbStandard")
        self.rdbSmart = QtWidgets.QRadioButton(parent=self.grpModelType)
        self.rdbSmart.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rdbSmart.setObjectName("rdbSmart")
        self.rdbLuxury = QtWidgets.QRadioButton(parent=self.grpModelType)
        self.rdbLuxury.setGeometry(QtCore.QRect(10, 90, 82, 17))
        self.rdbLuxury.setObjectName("rdbLuxury")
        self.lblDownPaymentHeader = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblDownPaymentHeader.setGeometry(QtCore.QRect(950, 70, 101, 16))
        self.lblDownPaymentHeader.setObjectName("lblDownPaymentHeader")
        self.lblDownPayment = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblDownPayment.setGeometry(QtCore.QRect(900, 100, 101, 16))
        self.lblDownPayment.setObjectName("lblDownPayment")
        self.txtDownPayment = QtWidgets.QLineEdit(parent=self.tbPurchase)
        self.txtDownPayment.setGeometry(QtCore.QRect(1020, 100, 113, 20))
        self.txtDownPayment.setObjectName("txtDownPayment")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tbPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(30, 340, 75, 23))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnShowPayments = QtWidgets.QPushButton(parent=self.tbPurchase)
        self.btnShowPayments.setGeometry(QtCore.QRect(570, 340, 111, 23))
        self.btnShowPayments.setObjectName("btnShowPayments")
        self.btnClear = QtWidgets.QPushButton(parent=self.tbPurchase)
        self.btnClear.setGeometry(QtCore.QRect(1140, 340, 75, 23))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tbPurchase)
        self.btnExit.setGeometry(QtCore.QRect(1210, 860, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.lblPayments = QtWidgets.QLabel(parent=self.tbPurchase)
        self.lblPayments.setGeometry(QtCore.QRect(570, 510, 121, 16))
        self.lblPayments.setObjectName("lblPayments")
        self.lstPayments = QtWidgets.QListWidget(parent=self.tbPurchase)
        self.lstPayments.setGeometry(QtCore.QRect(500, 550, 256, 192))
        self.lstPayments.setObjectName("lstPayments")
        self.tbHomePurchaseApplication.addTab(self.tbPurchase, "")
        self.tbPurchasesMade = QtWidgets.QWidget()
        self.tbPurchasesMade.setObjectName("tbPurchasesMade")
        self.lblPurchasesMade = QtWidgets.QLabel(parent=self.tbPurchasesMade)
        self.lblPurchasesMade.setGeometry(QtCore.QRect(610, 80, 111, 16))
        self.lblPurchasesMade.setObjectName("lblPurchasesMade")
        self.lstPurchasesMade = QtWidgets.QListWidget(parent=self.tbPurchasesMade)
        self.lstPurchasesMade.setGeometry(QtCore.QRect(540, 130, 256, 192))
        self.lstPurchasesMade.setObjectName("lstPurchasesMade")
        self.tbHomePurchaseApplication.addTab(self.tbPurchasesMade, "")
        homePurchaseApplication.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=homePurchaseApplication)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1367, 22))
        self.menubar.setObjectName("menubar")
        homePurchaseApplication.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=homePurchaseApplication)
        self.statusbar.setObjectName("statusbar")
        homePurchaseApplication.setStatusBar(self.statusbar)

        self.retranslateUi(homePurchaseApplication)
        self.tbHomePurchaseApplication.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(homePurchaseApplication)
        # Creating a dictionary that can store house types and the prices of them
        self.house_prices = {}
        # Load the prices from the houseprice file
        self.load_house_prices("houseprice.txt")
    
        self.btnPurchase.clicked.connect(self.purchase_house)
        
        self.btnShowPayments.clicked.connect(self.show_payments)
        
        self.btnClear.clicked.connect(self.clear_form)
        
        self.btnExit.clicked.connect(self.exit_app)
        
        self.tbHomePurchaseApplication.currentChanged.connect(self.load_purchases_made)
        
        # This function will load prices from the houseprice file
    def load_house_prices(self, filename):
        try:
            # Open the file in read mode
            with open(filename, "r") as f:
                for line in f:
                    data = line.split(",")
                    # Store the house type and make sure the price is integer
                    self.house_prices[data[0]] = int(data[1])
        # This will tell the user if the houseprice file is not found
        except FileNotFoundError:
            print("The file could not be opened")
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
            
    # This is the function that save all the info to purchases_made file       
    def purchase_house(self):
        # Get user info
        name = self.txtCustomerName.text()
        age = self.txtCustomerAge.text()
        house = self.cmbHouseType.currentText()
        down_payment = self.txtDownPayment.text()
        # Makes sure that none of the fields are blank
        if name == "" or age == "" or down_payment == "":
            msg = QMessageBox()
            msg.setText("Please fill all fields")
            msg.exec()
        else:
            try:
                # Makes sure that the age and down payment are actually numbers and not words
                int(age)
                int(down_payment)
                # Checks which model type is selected
                if self.rdbStandard.isChecked():
                    model = "Standard"
                elif self.rdbSmart.isChecked():
                    model = "Smart"
                elif self.rdbLuxury.isChecked():
                    model = "Luxury"
                else:
                    # Creates a message if there is no model type selected
                    msg = QMessageBox()
                    msg.setText("Please select a model type")
                    msg.exec()
                    return
                # Open in append mode and save purchase
                with open("Purchases_made.txt", "a") as f:
                    f.write(f"{name}    {age}    {house}    {model}    {down_payment}\n")
                # Shows a message that shows it was sucsessful
                msg = QMessageBox()
                msg.setText("Purchase saved successfully")
                msg.exec()
            # Shows error message incase anything is not correct
            except Exception as e:
                print(e)
                print(type(e))
                msg = QMessageBox()
                msg.setText("Please enter valid numbers for age and down payment")
                msg.exec()
    # This function does calculations and also shows monthy payment schedule     
    
    def show_payments(self):
        # Clears the list 
        self.lstPayments.clear()
        # Retrieves the user inputs
        name = self.txtCustomerName.text()
        age = self.txtCustomerAge.text()
        house = self.cmbHouseType.currentText()
        down_payment = self.txtDownPayment.text()
        # Check if any fields are blank
        if name == "" or age == "" or down_payment == "":
            msg = QMessageBox()
            msg.setText("Please fill all fields first")
            msg.exec()
        else:
            try:
                # Convert down paymerns to an integer
                down_payment_val = int(down_payment)
                # Look up the base price from dictionary
                base_price = self.house_prices[house]
                # Check which model type selected and calculate the price increase from slecting a different model
                if self.rdbStandard.isChecked():
                    final_price = base_price
                elif self.rdbSmart.isChecked():
                    final_price = base_price + (0.15 * base_price)
                elif self.rdbLuxury.isChecked():
                    final_price = base_price + (0.20 * base_price)
                else:
                    # Show error message if no model selected
                    msg = QMessageBox()
                    msg.setText("Please select a model type")
                    msg.exec()
                    return
                # Write down the load details to call upon later for loan calculation
                annual_interest = 0.07
                monthly_interest = annual_interest / 12
                months = 120
                loan_amount = final_price - down_payment_val
                # Loan calculation
                monthly_payment = loan_amount * monthly_interest * (1 + monthly_interest) ** months / ((1 + monthly_interest) ** months - 1)
                # Make the balance aligjnj with loan calculations
                balance = loan_amount
                # More calculations
                for month in range(1, months + 1):
                    interest_for_month = balance * monthly_interest
                    principal_for_month = monthly_payment - interest_for_month
                    balance = balance - principal_for_month
                    if balance < 0:
                        balance = 0
                    # Displays the month number, monthly payment, and remaining balance
                    display_line = "Month " + str(month) + ": $" + str(round(monthly_payment, 2)) + " | Balance $" + str(round(balance, 2))
                    self.lstPayments.addItem(display_line)
            # Shows error message if there is anything wrong
            except Exception as e:
                print(e)
                print(type(e))
                msg = QMessageBox()
                msg.setText("Error calculating payments")
                msg.exec()
    # This function loads purchases from the purchases_made file            
    def load_purchases_made(self):
        # This will run when the second tab is clicked
        if self.tbHomePurchaseApplication.currentIndex() == 1:
            # Clear the list 
            self.lstPurchasesMade.clear()
            try:
                # Opens the file in read mode
                with open("purchases_made.txt", "r") as f:
                    for line in f:
                        self.lstPurchasesMade.addItem(line)
            # Error message if the file is not found
            except FileNotFoundError:
                msg = QMessageBox()
                msg.setText("No purchases found")
                msg.exec()
            except Exception as e:
                print(e)
                print(type(e))
                
    # This function clears the form 
    def clear_form(self):
        self.txtCustomerName.clear()
        self.txtCustomerAge.clear()
        self.txtDownPayment.clear()
        self.cmbHouseType.setCurrentIndex(0)
        self.rdbStandard.setChecked(False)
        self.rdbSmart.setChecked(False)
        self.rdbLuxury.setChecked(False)
        self.lstPayments.clear()
        
    # This function exits the application   
    def exit_app(self):
        QtWidgets.QApplication.quit()
                
    
          
    def retranslateUi(self, homePurchaseApplication):
        _translate = QtCore.QCoreApplication.translate
        homePurchaseApplication.setWindowTitle(_translate("homePurchaseApplication", "Home Purchase"))
        self.lblCustomerName.setText(_translate("homePurchaseApplication", "Enter Name:"))
        self.lblCustomerAge.setText(_translate("homePurchaseApplication", "Enter Age:"))
        self.lblCustomerInfo.setText(_translate("homePurchaseApplication", "Customer Info"))
        self.lblHouse.setText(_translate("homePurchaseApplication", "House"))
        self.cmbHouseType.setItemText(0, _translate("homePurchaseApplication", "Apartment"))
        self.cmbHouseType.setItemText(1, _translate("homePurchaseApplication", "TownHouse"))
        self.cmbHouseType.setItemText(2, _translate("homePurchaseApplication", "Single-Family Home"))
        self.cmbHouseType.setItemText(3, _translate("homePurchaseApplication", "Luxury Villa"))
        self.lblHouseType.setText(_translate("homePurchaseApplication", "House Type:"))
        self.lblModel.setText(_translate("homePurchaseApplication", "Model"))
        self.grpModelType.setTitle(_translate("homePurchaseApplication", "Model Type"))
        self.rdbStandard.setText(_translate("homePurchaseApplication", "Standard"))
        self.rdbSmart.setText(_translate("homePurchaseApplication", "Smart"))
        self.rdbLuxury.setText(_translate("homePurchaseApplication", "Luxury"))
        self.lblDownPaymentHeader.setText(_translate("homePurchaseApplication", "Down Payment"))
        self.lblDownPayment.setText(_translate("homePurchaseApplication", "Down Payment:"))
        self.btnPurchase.setText(_translate("homePurchaseApplication", "Purchase"))
        self.btnShowPayments.setText(_translate("homePurchaseApplication", "Show Payments"))
        self.btnClear.setText(_translate("homePurchaseApplication", "Clear"))
        self.btnExit.setText(_translate("homePurchaseApplication", "Exit"))
        self.lblPayments.setText(_translate("homePurchaseApplication", "Payment Schedule"))
        self.tbHomePurchaseApplication.setTabText(self.tbHomePurchaseApplication.indexOf(self.tbPurchase), _translate("homePurchaseApplication", "Purchase"))
        self.lblPurchasesMade.setText(_translate("homePurchaseApplication", "Purchases Made"))
        self.tbHomePurchaseApplication.setTabText(self.tbHomePurchaseApplication.indexOf(self.tbPurchasesMade), _translate("homePurchaseApplication", "Purchases Made"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homePurchaseApplication = QtWidgets.QMainWindow()
    ui = Ui_homePurchaseApplication()
    ui.setupUi(homePurchaseApplication)
    homePurchaseApplication.show()
    sys.exit(app.exec())
